* src/plugins/WebPage.py: Fixed ID link so that link references are not converted to &lt; and &gt; * src/plugins/WriteGedcom.py: Fixed undefined reference to ref_text
git-svn-id: svn+ssh://svn.code.sf.net/p/gramps/code/trunk/gramps2@2205 4ae1f11a-8b86-4847-b8af-ab372f36d1fd