Reviving RunAllTests.py on gramps40/trunk
Porting from gramps34 my fix for 6935, 6937, 6938.

Import with full "gramps." qualification from the tests,
to overcome the relative import problem (see bug# 6938 for context).

All testing code has been adjusted to the filename and paths
changes since gramps34.
Same as on gramps34, one test fails still, will investigate if
it is a test or a code bug:
    ERROR: test_buffer_recall
    (ErrorReportAssistant_Test.ErrorReportAssistantTest)
    Test that simple recall of messages works.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./GrampsLogger/ErrorReportAssistant_Test.py", line 60, in
    test_buffer_recall
        rotate_handler=rh)
      File "../gramps/gui/logger/_errorreportassistant.py", line 81, in
    __init__
        self.build_page1()
      File "../gramps/gui/logger/_errorreportassistant.py", line 267, in
    build_page1
        self._reset_error_details()
      File "../gramps/gui/logger/_errorreportassistant.py", line 178, in
    _reset_error_details
        self._error_detail.get_record()))
    AttributeError: 'str' object has no attribute 'get_record'

git-svn-id: svn+ssh://svn.code.sf.net/p/gramps/code/branches/maintenance/gramps40@22729 4ae1f11a-8b86-4847-b8af-ab372f36d1fd