7045: Date.set on invalid date does not raise
Now it does, but another test breaks:

Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/vassilii/Gramps/gramps/gen/lib/test/date_test.py", line 136, in <module>
    d.set(quality,modifier,calendar,(4,11,-90,False),"Text comment")
  File "/home/vassilii/Gramps/gramps/gen/lib/date.py", line 1600, in set
    format(original, value))
DateError: Invalid year -90 passed in value (4, 11, -90, False)

because the corresponding year gets adjusted from -90 to 1...

git-svn-id: svn+ssh://svn.code.sf.net/p/gramps/code/trunk@23121 4ae1f11a-8b86-4847-b8af-ab372f36d1fd